import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Personal Portfolio</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h2 className={styles.title}>
                    Education
                </h2>

                <div style="display:inline-block;vertical-align:top;">
                    <Image src="/WPI_logo.png" layout='responsive' width={500} height={500}/>
                </div>
                <div style="display:inline-block;">
                    <p className={styles.description}>
                        What I've Learned
                    </p>
                </div>
            </main>
        </div>
    )
}
