import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Personal Portfolio</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <div>
                    <h2 className={styles.title}>
                        Education
                    </h2>

                    <div class="flex items-center gap-10">
                        <Image src="/WPI_logo.png" width={250} height={250}/>
                        <p className={styles.description}>
                            What I've Learned
                        </p>
                    </div>
                </div>
            </main>
        </div>
    )
}
