import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";

export default function Home() {
		return (
				<div className={styles.container}>
						<Head>
								<title>Personal Portfolio</title>
								<meta
										name="description"
										content="Generated by create next app"
								/>
								<link rel="icon" href="/favicon.ico" />
						</Head>

						<main className={styles.main}>
								<h1 className={styles.title}>Owen Sullivan</h1>

								<p className={styles.description}>My Personal Portfolio</p>

								<div className={styles.grid}>
										<a Link href="/experience" className={styles.card}>
												<h2>Experience &rarr;</h2>
												<p>
														Lorem ipsum dolor sit amet, consectetur adipiscing
														elit, sed do eiusmod tempor incididunt ut labore et
														dolore magna aliqua.
												</p>
										</a>

										<a Link href="/education" className={styles.card}>
												<h2>Education &rarr;</h2>
												<p>
														Lorem ipsum dolor sit amet, consectetur adipiscing
														elit, sed do eiusmod tempor incididunt ut labore et
														dolore magna aliqua.
												</p>
										</a>

										<a Link href="/projects" className={styles.card}>
												<h2>Projects &rarr;</h2>
												<p>
														Lorem ipsum dolor sit amet, consectetur adipiscing
														elit, sed do eiusmod tempor incididunt ut labore et
														dolore magna aliqua.
												</p>
										</a>

										<a Link href="/hobbies" className={styles.card}>
												<h2>Hobbies &rarr;</h2>
												<p>
														Lorem ipsum dolor sit amet, consectetur adipiscing
														elit, sed do eiusmod tempor incididunt ut labore et
														dolore magna aliqua.
												</p>
										</a>
								</div>
						</main>

						<footer className={styles.footer}>
								<a
										href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
										target="_blank"
										rel="noopener noreferrer"
								>
										Powered by{" "}
										<span className={styles.logo}>
												<Image
														src="/vercel.svg"
														alt="Vercel Logo"
														width={72}
														height={16}
												/>
										</span>
								</a>
						</footer>
				</div>
		);
}
